apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-dxl-sor-accountmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-dxl-sor-accountmanagement
  template:
    metadata:
      annotations:     
        prometheus.io/scrape: "true"
        prometheus.io/name: 'geenrated-app'
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
      labels:
        app: ms-dxl-sor-accountmanagement
   
    spec:
      hostAliases:
      - ip: "10.94.163.123"
        hostnames:
        - "eai.sit.ndc3.app.vodafoneidea.in"
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ms-dxl-sor-accountmanagement
        image: vidxlcidacr.azurecr.io/ms-dxl-sor-account:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 6381
          name: micro
        env:
        
          - name: CONFIG_PUSHGATEWAY_URL
            valueFrom:
                configMapKeyRef:
                    name: config-pushgateway-url
                    key: PUSHGATEWAY_URL_SPRING_BOOT

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name          
          
          - name: APPLICATION_PROFILE_KEY
            valueFrom:
              configMapKeyRef:
                name: config-dxl-environment
                key: DXL_ENVIRONMENT
                
          - name: DXL_SOR_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: config-dxl-log-level
                key: DXL_SOR_LOG_LEVEL 
                  
          - name: DXL_API_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: config-dxl-log-level-v2
                key: DXL_API_LOG_LEVEL
          
                
          - name: JMS_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: jms_timeout   
                
          - name: SESSION_CACHE_SIZE
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: session-cache-size
                
          - name: DOX_INPUT_KEY
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: doxInputKey
           
          - name: DOX_OUTPUT_KEY
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: doxOutputKey   
        
          - name: DOX_MQ_CHANNEL
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: dox_mq_channel
                
          - name: DOX_MQ_QUEUE_MANAGER
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: dox_mq_mgr
                                       
          - name: DOX_MQ_CONN_NAME
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: dox_mq_connName
          
          - name: CACHE_CONSUMERS
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: cache-consumers
          - name: RECONNECT_ON_EXCEPTION
                      
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: reconnect-on-connection           
          - name: DOX_MQ_SSL_CIPHER
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: ssl-cipher     
                    
          - name: DOX_MQ_IBM_CIPHER_MAPPINGS
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: ibm-cipher-mappings         
                
          - name: DOX_MQ_USER_AUTHENTICATION
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: user-authentication
                       
          - name: IDEA_BSCS_DATABASE_PLATFORM
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: idea_bscs_db_datasource_platform
          
          - name: IDEA_BSCS_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: idea_bscs_db_datasource_url
        
          - name: IDEA_BSCS_DATASOURCE_DRIVER_CLASS
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: idea_bscs_db_driver_class
          
          - name: IDEA_BSCS_DATASOURCE_MAX_LIFETIME
            valueFrom:
              configMapKeyRef:
                name: config-idea-bscs-db
                key: idea_bscs_db_max_lifetime
          - name: IDEA_BSCS_DATASOURCE_IDEL_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config-idea-bscs-db
                key: idea_bscs_db_idel_timeout
          - name: IDEA_BSCS_DATASOURCE_MIN_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                name: config-idea-bscs-db
                key: idea_bscs_db_minpool_size
          - name: IDEA_BSCS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-idea-bscs-db
                key: secret_idea_bscs_username
        
          - name: IDEA_BSCS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-idea-bscs-db
                key: secret_idea_bscs_password
        
          - name: IDEA_BSCS_DATASOURCE_CONNECTION_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: idea_bscs_db_connection_timeout
        
          - name: IDEA_BSCS_DATASOURCE_MAX_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                name: config-dxl-sor-account
                key: idea_bscs_db_maxpool_size  
                   
          - name: MQ_USER
            valueFrom:
              secretKeyRef:
                name: secret-mq-mock
                key: mq_username
                
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-mq-mock
                key: mq_password

          - name: ZIPKIN_URL
            valueFrom:
              configMapKeyRef:
                name: config-sor-zipkin
                key: zipkin_url
          - name: ZIPKIN_ENABLED
            valueFrom:
              configMapKeyRef:
                name: config-sor-zipkin
                key: zipkin_enabled         
          - name: GET_ADDON_SUBSCRIBER_LIST_URL
            valueFrom:
              configMapKeyRef:
                name: config-sor-addon-customer
                key: get_addon_subscriber_list_url
          - name: GET_ADDON_SUBSCRIBER_LIST_AUTH_TOKEN
            valueFrom:
              configMapKeyRef:
                name: config-sor-addon-customer
                key: get_addon_subscriber_list_auth_token
          - name: GET_ADDON_SUBSCRIBER_LIST_READ_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config-sor-addon-customer
                key: get_addon_subscriber_list_read_timeout
          - name: GET_ADDON_SUBSCRIBER_LIST_CONN_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config-sor-addon-customer
                key: get_addon_subscriber_list_conn_timeout        
---
apiVersion: v1
kind: Service
metadata:
  name: ms-dxl-sor-accountmanagement
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.98.43.126
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ms-dxl-sor-accountmanagement

